### ISSUE TITLE
Sentinel Shield & Passive Perception

### ISSUE THREAD

**Issue by sagnam** [ceryliae/DnDAppFiles#133]
I think the entry for Sentinel Shield needs and additional:

```
    <modifier category="bonus">passive wisdom +5</modifier>
```

**Comment by ceryliae** [comment]
Hi,

I remember reading somewhere that advantage on a roll is equal to a +5 for passives, but I don't remember where it was. I think it was in the DMG somewhere. Can you provide me a page number for the rule, because if it's a variant rule then I will have to discuss whether or not to add it to the files. If we accommodated every variant rule, it would be a mess.

J

**Comment by sagnam** [comment]
Basic Rules, pg. 59

"If the character has advantage on the check, add 5. For disadvantage, subtract 5."

**Comment by ceryliae** [comment]
Will fix that later today

**Comment by ceryliae** [comment]
Fixed
