### ISSUE TITLE
Git noob

### ISSUE THREAD

**Issue by CnrDmr** [ceryliae/DnDAppFiles#330]
I'm a complete git noob. I found this link thru reddit I think. I've been using the app for quite a while now.

Can I ask which books are included in these files? Is it being updated? The dropbox files I used do not have Xanathar's and any book that came after that so it's quite old.

**Comment by Jaffa5** [comment]
unfortanatly this hasn't been updated since 2017 i belive. i'm unsure if any of the forks are being updated ether. I have been recently using https://github.com/kinkofer/FightClub5eXML as an alternitive in the last couple weeks. it seems to be upto date and includeds all the books and unearthed arcana as far as i can tell.

**Comment by CnrDmr** [comment]
Alright I'll take a look at the link you posted, thanks!
